sudo: required
services:
    - docker
before_install:
    - docker build -t pgdaniel/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pgdaniel/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "dockerz"
    env: "Dockerz-env"
    bucket_name: "elasticbeanstalk-us-west-1-890081387597"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"